update all tools used to generate target files and ota package
Change-Id: I605d03384c0211fc917d003b56fd6a587006ee7f

diff --git a/releasetools/ota_target_from_phone b/releasetools/ota_target_from_phone
--- a/releasetools/ota_target_from_phone
+++ b/releasetools/ota_target_from_phone
@@ -1,102 +1,286 @@
 #!/bin/bash 
 
-TARGET_TOOL_PATH=$PORT_ROOT/tools/releasetools
-OTA_FROM_TARGET_FILES=$PORT_ROOT/tools/releasetools/ota_from_target_files
+PWD=`pwd`
+TOOL_DIR=$PORT_ROOT/tools
+OTA_FROM_TARGET_FILES=$TOOL_DIR/releasetools/ota_from_target_files
+TARGET_FILES_TEMPLATE_DIR=$PORT_ROOT/tools/target_files_template
+OUTPUT_DIR=$PWD/out
+TARGET_FILES_DIR=$OUTPUT_DIR/target_files
+RECOVERY_ETC_DIR=$TARGET_FILES_DIR/RECOVERY/RAMDISK/etc
+SYSTEM_DIR=$TARGET_FILES_DIR/SYSTEM
+META_DIR=$TARGET_FILES_DIR/META
+TARGET_FILES_ZIP=$OUTPUT_DIR/target_files.zip
+OUTPUT_OTA_PACKAGE=$OUTPUT_DIR/update.zip
+FULL_OTA_PACKAGE=$2
+MODE=$1
 
-TARGET_FILES_TEMPLATE_PATH=$PORT_ROOT/tools/target_files_template
+# prompt user
+function prompt_user {
+    echo "ota_target_from_phone -n|-r [ota-package]"
+    echo "  -n: run this script in normal mode"
+    echo "  -r: run this script in recovery mode, if you can run adb in recovery mode, use this option"
+    echo "  ota-package: the stock full OTA package which already installed into your phone."
+    echo "               If you can't find a OTA package, this can be empty and we will generate"
+    echo "               a OTA package for you to use for our make process"
+    echo
+    echo "Before running this script, please ensure: "
+    echo "(1) The phone is connected to PC and turn on USB Debug"
+    echo "(2) The phone has a rooted kernel or have root privilege"
+    echo
+    echo "This script will generate two zip files under $OUTPUT_DIR: "
+    echo "(1) target_files.zip: this is used to generate incremental OTA package"
+    echo "(2) update.zip: OTA package you can use if you don't have one. This package is ok to install in recovery"
+    echo
+}
 
-TARGET_FILES_PATH=`pwd`/out/target_files
-RECOVERY_PATH=$TARGET_FILES_PATH/RECOVERY/RAMDISK/etc
-SYSTEM_PATH=$TARGET_FILES_PATH/system
-META_PATH=$TARGET_FILES_PATH/META
-ZIP_NAME=target_files.zip
-OTA_PACKAGE_PATH=`pwd`/out
-OTA_PACKAGE_NAME=update.zip
+# copy the whole target_files_template dir
+function copy_target_files_template {
+    echo "Copy target file template into current working directory"
+    rm -rf $TARGET_FILES_DIR
+    rm -f $TARGET_FILES_ZIP
+    rm -f $OUTPUT_OTA_PACKAGE
+    mkdir -p $TARGET_FILES_DIR
+    cp -r $TARGET_FILES_TEMPLATE_DIR/* $TARGET_FILES_DIR
+}
 
-mkdir -p $TARGET_FILES_PATH
-cp -r $TARGET_FILES_TEMPLATE_PATH/*  $TARGET_FILES_PATH
+# wait for the device to be online or timeout
+function wait_for_device_online {
+    echo "Wait for the device to be online..."
 
-adb reboot recovery
-echo "please wait for reboot the phone....."
-sleep 30
+    TIMEOUT=120
+    while [ $TIMEOUT -gt 0 ]
+    do
+        if adb shell ls > /dev/null
+        then
+            break
+        fi
+        sleep 30
+        TIMEOUT=$[$TIMEOUT - 30]
+    done
+}
 
-while [ 0 ]
-do 
-    adb shell pwd
-    if [ $? -eq 0 ]
+function ask_for_boot_image {
+    echo "Warning: the ota package will not contain bootimage!!!"
+    echo "Maybe you forget to pass the ota-package parameter."
+    answer="no"
+    while [ 1 ]
+    do
+        echo -n "Are you sure this is really what you want(yes/no):"
+        read answer
+        if [ "$answer" == "no" ];then
+            exit 0
+        elif [ "$answer" == "yes" ];then
+            return
+        fi
+    done
+}
+
+# In normal mode, extract the boot image from full ota package
+function extract_bootimage {
+    if [ -z $FULL_OTA_PACKAGE ]
     then
-        break
-    else
-        sleep 5
+        ask_for_boot_image
+        return
     fi
-done
 
-#######################################################################
-info=`adb shell cat /etc/recovery.fstab | grep boot | sed -e "s/\s\+/:/g"`
- 
-type=`echo $info | cut -d":" -f2`
- 
-if [ "$type" == "mtd" ]; then
-        mtdn=`adb shell cat /proc/mtd | grep boot | cut -f1 -d":"`
-        where=/dev/$type/$mtdn
-elif [ "$type" == "emmc" ]; then
-        where=`echo $info | cut -d":" -f3`
+    echo "Extract bootimage from full ota package"
+    local tempdir=`mktemp -d dir.XXXXXX`
+    unzip -q $FULL_OTA_PACKAGE -d $tempdir
+    for file in boot.img zImage */boot.img */zImage
+    do
+        if [ -f $tempdir/$file ]
+        then
+            cp $tempdir/$file $TARGET_FILES_DIR/BOOTABLE_IMAGES/boot.img
+            rm -rf $tempdir
+            return
+        fi
+    done
+    ask_for_boot_image
+}
+
+# In recovery mode, dump the boot image from device
+function dump_bootimage {
+    echo "Dump bootimage from device"
+    if [ -f dumpimage.sh ]
+    then
+        ./dumpimage.sh $TARGET_FILES_DIR/BOOTABLE_IMAGES
+    else
+        local info=`adb shell cat /etc/recovery.fstab | grep boot | sed -e "s/\s\+/:/g"`
+        local fstype=`echo $info | cut -d":" -f2`
+
+        if [ "$fstype" == "mtd" ]; then
+            mtdn=`adb shell cat /proc/mtd | grep boot | cut -f1 -d":"`
+            device=/dev/$fstype/$mtdn
+        else
+            device=`echo $info | cut -d":" -f3`
+        fi
+        adb pull $device $TARGET_FILES_DIR/BOOTABLE_IMAGES/boot.img
+    fi
+}
+
+# In recovery mode, extract the recovery.fstab from device
+function extract_recovery_fstab {
+    echo "Extract recovery.fstab from device"
+    adb shell cat /etc/recovery.fstab > $RECOVERY_ETC_DIR/recovery.fstab
+}
+
+# In normal mode, build the recovery.fstab from device
+function build_recovery_fstab {
+    if [ -f recovery.fstab ]
+    then
+        cp recovery.fstab $RECOVERY_ETC_DIR/recovery.fstab
+        return
+    elif [ -n "$FULL_OTA_PACKAGE" ]
+    then
+		echo $FULL_OTA_PACKAGE
+        echo "You should provide a recovery.fstab file in your working directory."
+        exit 1
+    fi
+
+    echo "Build recovery.fstab from device"
+    IFS_OLD=$IFS
+    IFS=$'\n'
+    cat /dev/null > $RECOVERY_ETC_DIR/recovery.fstab
+    for line in `adb shell cat /proc/mounts | grep -E "/system|/data|/cache" | cut -d " " -f1-3`
+    do
+        mount_fstype=`echo $line | cut -d " " -f2,3`
+        device=`echo $line | cut -d " " -f1`
+        echo $mount_fstype $device >> $RECOVERY_ETC_DIR/recovery.fstab
+    done
+    IFS=$IFS_OLD
+}
+
+# build filesystem_config.txt from device
+function build_filesystem_config {
+    echo "Run getfilesysteminfo to build filesystem_config.txt"
+
+    adb push $TOOL_DIR/releasetools/getfilesysteminfo /system/xbin
+    adb shell chmod 0777 /system/xbin/getfilesysteminfo
+    adb shell /system/xbin/getfilesysteminfo --info /system >> $META_DIR/filesystem_config.txt
+    cat $META_DIR/filesystem_config.txt | col -b | sed -e '/getfilesysteminfo/d' > $META_DIR/tmp.txt
+    cat $META_DIR/tmp.txt | sort > $META_DIR/filesystem_config.txt
+    rm $META_DIR/tmp.txt
+}
+
+# recover the device files' symlink information
+function recover_symlink {
+    echo "Run getfilesysteminfo and recoverylink.py to recover symlink"
+
+    adb shell /system/xbin/getfilesysteminfo --link /system | sort > $SYSTEM_DIR/linkinfo.txt
+    python $TOOL_DIR/releasetools/recoverylink.py $TARGET_FILES_DIR
+    rm $SYSTEM_DIR/linkinfo.txt
+    adb shell rm /system/xbin/getfilesysteminfo
+}
+
+function remount_system_device {
+    echo "Remount /system to be writable"
+
+    if adb root | grep "cannot run" > /dev/null
+    then
+        device=`adb shell cat /proc/mounts | grep "/system" | cut -d " " -f 1`
+        echo "You don't have a rooted kernel. Please run the following command mannually"
+        echo "(1) adb shell"
+        echo "(2) su"
+        echo "(3) mount -o remount,rw $device /system"
+        echo "(3) chmod 0777 /system /system/*"
+        echo
+
+        answer="no"
+        while [ $answer != "yes" ]
+        do
+            echo -n "If you finish running the above commands on your phone(yes/no):"
+            read answer
+        done
+
+        if adb push $TOOL_DIR/releasetools/getfilesysteminfo /system/xbin
+        then
+            return
+        else
+            echo "Please double check your answer and if your phone has root privilege"
+            exit 1
+        fi
+    else
+        sleep 1
+        adb remount
+    fi
+    sleep 1
+}
+
+# build the SYSTEM dir under target_files
+function build_SYSTEM {
+    echo "Extract the whole /system from device"
+    adb pull /system $SYSTEM_DIR
+    remount_system_device
+    build_filesystem_config
+    recover_symlink
+}
+
+# compress the target_files dir into a zip file
+function zip_target_files {
+    echo "Compress the target_files dir into zip file"
+    cd $TARGET_FILES_DIR
+    zip -q -r -y $TARGET_FILES_ZIP *
+}
+
+# build a new full ota package
+function build_ota_package {
+    echo "Build full ota package: $OUTPUT_OTA_PACKAGE"
+    $OTA_FROM_TARGET_FILES -n -k $TOOL_DIR/platform $TARGET_FILES_ZIP $OUTPUT_OTA_PACKAGE
+}
+
+# try to generate the full ota package and target files in recovery mode
+function try_recovery_mode {
+    echo "Reboot into recovery mode to generate target files..."
+    adb reboot recovery
+    wait_for_device_online
+    if [ $TIMEOUT -eq 0 ]
+    then
+        return
+    fi
+    dump_bootimage
+    extract_recovery_fstab
+    adb shell mount /system
+    sleep 5
+    build_SYSTEM
+    zip_target_files
+    build_ota_package
+    adb shell umount /system
+    exit 0
+}
+
+# try to generate the full ota package and target files in normal mode
+function try_normal_mode {
+    wait_for_device_online
+    if [ $TIMEOUT -eq 0 ]
+    then
+        echo "Can't find the device, please check if you turn on the USB Debug, then rerun this script"
+        exit 1
+    fi    
+    extract_bootimage
+    build_recovery_fstab
+    build_SYSTEM
+    zip_target_files
+    build_ota_package
+    exit 0
+}
+
+if [ $# -eq 0 ] || [ $# -gt 2 ] 
+then
+    prompt_user
+    exit 1
+fi
+
+if [ "$MODE" != "-r" ] && [ "$MODE" != "-n" ]
+then
+    prompt_user
+    exit 1
+fi
+
+copy_target_files_template
+
+if [ "$MODE" == "-r" ]
+then
+    try_recovery_mode
 else
-    exit 1
+    try_normal_mode
 fi
-
-adb shell mount /system
-
-echo "Get bootimage from $where"
-
-adb push $TARGET_TOOL_PATH/getbootimage /sbin
-adb shell . getbootimage "$where"
-adb pull /boot.img $TARGET_FILES_PATH/BOOTABLE_IMAGES/
-#######################################################################
-
-rm $RECOVERY_PATH/recovery.fstab
-adb shell cat /etc/recovery.fstab > $RECOVERY_PATH/recovery.fstab
-
-sleep 1
-
-adb push $TARGET_TOOL_PATH/getfilesysteminfo /system/xbin
-
-rm -rf $SYSTEM_PATH
-rm -rf $TARGET_FILES_PATH/SYSTEM
-mkdir $SYSTEM_PATH
-
-rm $META_PATH/filesystem_config.txt
-adb shell /system/xbin/getfilesysteminfo --info /system > $META_PATH/tmp.txt
-more $META_PATH/tmp.txt | sed 's/\r//g' | sort > $META_PATH/filesystem_config.txt
-rm $META_PATH/tmp.txt
-
-adb shell /system/xbin/getfilesysteminfo --link /system > $SYSTEM_PATH/tmp.txt
-more $SYSTEM_PATH/tmp.txt | sort > $SYSTEM_PATH/linkinfo.txt
-rm $SYSTEM_PATH/tmp.txt
-
-adb pull /system $SYSTEM_PATH
-
-echo "mv $SYSTEM_PATH $TARGET_FILES_PATH/SYSTEM"
-mkdir $TARGET_FILES_PATH/SYSTEM
-mv $SYSTEM_PATH/* $TARGET_FILES_PATH/SYSTEM
-rm -rf $SYSTEM_PATH
-
-python $TARGET_TOOL_PATH/recoverylink.py "$TARGET_FILES_PATH"
-if [ $? -ne 0 ]; then
-    echo "Error: recovery link files failed"
-    exit 1
-fi
-rm $TARGET_FILES_PATH/SYSTEM/linkinfo.txt
-
-adb reboot
-
-cd "$TARGET_FILES_PATH"
-rm -rf $OTA_PACKAGE_PATH/$ZIP_NAME
-zip -r -y $OTA_PACKAGE_PATH/$ZIP_NAME ./*
-cd -
-
-echo "python $OTA_FROM_TARGET_FILES $OTA_PACKAGE_PATH/$ZIP_NAME $OTA_PACKAGE_PATH/$OTA_PACKAGE_NAME"
-python $OTA_FROM_TARGET_FILES $OTA_PACKAGE_PATH/$ZIP_NAME $OTA_PACKAGE_PATH/$OTA_PACKAGE_NAME
-
-#rm -rf $OTA_PACKAGE_PATH/$ZIP_NAME
-
